"""Puerto reducido al ejercicio anual; las cédulas usan PoaFormRepository."""

from typing import Protocol

from ..entities import PoaExercise


class PoaRepository(Protocol):
    async def add_exercise(self, item: PoaExercise) -> None: ...
    async def get_exercise(self, item_id: int) -> PoaExercise | None: ...
    async def list_exercises(self) -> list[PoaExercise]: ...
    async def update_exercise(self, item: PoaExercise) -> None: ...
