"""Puertos de persistencia de la planeacion POA."""

from __future__ import annotations

from typing import Protocol

from ..entities import PoaActivity, PoaExercise, PoaObjective, PoaProcess


class PoaRepository(Protocol):
    async def add_exercise(self, item: PoaExercise) -> None: ...
    async def add_process(self, item: PoaProcess) -> None: ...
    async def add_objective(self, item: PoaObjective) -> None: ...
    async def add_activity(self, item: PoaActivity) -> None: ...
    async def get_exercise(self, item_id: int) -> PoaExercise | None: ...
    async def get_process(self, item_id: int) -> PoaProcess | None: ...
    async def get_objective(self, item_id: int) -> PoaObjective | None: ...
    async def get_activity(self, item_id: int) -> PoaActivity | None: ...
    async def update_activity(self, item: PoaActivity) -> None: ...
    async def list_activities(self, *, area_id: int | None = None) -> list[PoaActivity]: ...


class ValidatedAdvanceReader(Protocol):
    async def has_validated_for_activity(self, activity_id: int) -> bool: ...
