"""Puertos del seguimiento POA."""

from __future__ import annotations

from typing import Protocol

from ..entities import PoaAdvance


class PoaAdvanceRepository(Protocol):
    async def add(self, item: PoaAdvance) -> None: ...
    async def get_by_id(self, item_id: int) -> PoaAdvance | None: ...
    async def get_by_activity_quarter(
        self, activity_id: int, quarter: int
    ) -> PoaAdvance | None: ...
    async def update(self, item: PoaAdvance) -> None: ...
    async def list_by_activity(self, activity_id: int) -> list[PoaAdvance]: ...
    async def list_by_capturer(self, capturer_id: int) -> list[PoaAdvance]: ...
    async def has_validated_for_activity(self, activity_id: int) -> bool: ...
    async def reset_validated_for_period(self, period_id: int, actor_id: int) -> None: ...


class ReferenceReader(Protocol):
    async def get_by_id(self, item_id: int): ...


class EvidenceReader(Protocol):
    async def has_for(self, entity, entity_id: int) -> bool: ...
