from typing import Protocol

from ..entities import Notification


class NotificationRepository(Protocol):
    async def create(self, notification: Notification) -> Notification: ...
    async def list_for_user(
        self,
        user_id: int,
        unread_only: bool = False,
    ) -> list[Notification]: ...
    async def mark_read(self, notification_id: int, user_id: int) -> None: ...
    async def mark_email_sent(self, notification_id: int) -> None: ...
    async def pending_email(self, limit: int = 100, after_id: int = 0) -> list[Notification]: ...
    async def claim_email(self, notification_id: int) -> bool: ...
    async def release_email(self, notification_id: int) -> None: ...
