"""Interfaces segregadas para areas e instrumentos."""

from __future__ import annotations

from typing import Protocol

from ..entities import Area, Instrument
from ..reference_entities import ReferenceItem
from ..unit_of_measure_entities import UnitOfMeasure


class AreaRepository(Protocol):
    async def add(self, area: Area) -> None: ...

    async def list(self, *, active_only: bool = True) -> list[Area]: ...

    async def get_by_id(self, area_id: int) -> Area | None: ...

    async def update(self, area: Area) -> None: ...


class InstrumentRepository(Protocol):
    async def add(self, instrument: Instrument) -> None: ...

    async def list(self, *, active_only: bool = True) -> list[Instrument]: ...

    async def get_by_id(self, instrument_id: int) -> Instrument | None: ...

    async def update(self, instrument: Instrument) -> None: ...


class ReferenceRepository(Protocol):
    async def add(self, item: ReferenceItem) -> None: ...

    async def get_by_id(self, item_id: int) -> ReferenceItem | None: ...

    async def list(self, *, active_only: bool = True) -> list[ReferenceItem]: ...

    async def update(self, item: ReferenceItem) -> None: ...


class UnitOfMeasureRepository(Protocol):
    async def add(self, item: UnitOfMeasure) -> None: ...

    async def get_by_id(self, item_id: int) -> UnitOfMeasure | None: ...

    async def list(self, *, active_only: bool = True) -> list[UnitOfMeasure]: ...

    async def update(self, item: UnitOfMeasure) -> None: ...
